import type {
  Account,
  Bill,
  Beneficiary,
  Card,
  Transaction,
  User,
  Holding,
  SIP,
  InsurancePolicy,
  Loan,
  FinancialGoal,
  PropertyAsset,
} from './types'

export const initialUser: User = {
  id: 'u1',
  fullName: 'Aarav Mehta',
  email: 'aarav.mehta@email.com',
  phone: '+91 98765 43210',
  customerId: 'CIF1029384756',
  kycStatus: 'verified',
}

export const initialAccounts: Account[] = [
  {
    id: 'a1',
    name: 'HDFC Savings',
    type: 'savings',
    accountNumber: '••••4521',
    balance: 487250,
    availableBalance: 487250,
    bankName: 'HDFC Bank',
    ifsc: 'HDFC0001234',
    gradient: 'from-blue-600 to-indigo-700',
  },
  {
    id: 'a2',
    name: 'ICICI Current',
    type: 'current',
    accountNumber: '••••8830',
    balance: 112400,
    availableBalance: 112400,
    bankName: 'ICICI Bank',
    ifsc: 'ICIC0004567',
    gradient: 'from-orange-500 to-red-600',
  },
  {
    id: 'a3',
    name: 'HDFC Millennia Credit',
    type: 'credit_card',
    accountNumber: '••••1147',
    balance: 18750, // outstanding
    creditLimit: 250000,
    availableBalance: 231250,
    bankName: 'HDFC Bank',
    gradient: 'from-slate-700 to-slate-900',
  },
  {
    id: 'a4',
    name: 'SBI Salary',
    type: 'savings',
    accountNumber: '••••9902',
    balance: 62300,
    availableBalance: 62300,
    bankName: 'State Bank of India',
    ifsc: 'SBIN0009988',
    gradient: 'from-violet-600 to-purple-800',
  },
]

// Build dates relative to May 25, 2026
const d = (daysAgo: number, h = 10, m = 30): string => {
  const base = new Date('2026-05-25T10:30:00+05:30')
  base.setDate(base.getDate() - daysAgo)
  base.setHours(h, m, 0, 0)
  return base.toISOString()
}

export const initialTransactions: Transaction[] = [
  // Recent (newest first conceptually; we will sort in selectors)
  { id: 't1', accountId: 'a1', date: d(0, 9, 12), merchant: 'Swiggy', description: 'Lunch order', amount: 387, type: 'debit', category: 'food', mode: 'UPI', status: 'completed' },
  { id: 't2', accountId: 'a3', date: d(0, 20, 5), merchant: 'Starbucks', description: 'Coffee', amount: 485, type: 'debit', category: 'food', mode: 'CARD', status: 'completed' },
  { id: 't3', accountId: 'a1', date: d(1, 19, 40), merchant: 'Zomato', description: 'Dinner', amount: 512, type: 'debit', category: 'food', mode: 'UPI', status: 'completed' },
  { id: 't4', accountId: 'a1', date: d(1, 8, 15), merchant: 'Uber', description: 'Ride to office', amount: 245, type: 'debit', category: 'transport', mode: 'UPI', status: 'completed' },
  { id: 't5', accountId: 'a2', date: d(2, 14, 22), merchant: 'BigBasket', description: 'Weekly groceries', amount: 2340, type: 'debit', category: 'shopping', mode: 'UPI', status: 'completed' },
  { id: 't6', accountId: 'a1', date: d(2, 18, 5), merchant: 'Rahul Singh', description: 'UPI/rahul@okhdfc', amount: 1500, type: 'debit', category: 'transfer', mode: 'UPI', status: 'completed' },
  { id: 't7', accountId: 'a3', date: d(3, 12, 0), merchant: 'Amazon', description: 'Electronics', amount: 1899, type: 'debit', category: 'shopping', mode: 'CARD', status: 'completed' },
  { id: 't8', accountId: 'a1', date: d(3, 7, 45), merchant: 'Ola', description: 'Auto ride', amount: 180, type: 'debit', category: 'transport', mode: 'UPI', status: 'completed' },
  { id: 't9', accountId: 'a1', date: d(4, 21, 30), merchant: 'Netflix', description: 'Monthly subscription', amount: 649, type: 'debit', category: 'entertainment', mode: 'UPI', status: 'completed' },
  { id: 't10', accountId: 'a1', date: d(4, 11, 10), merchant: 'Sneha Patel', description: 'UPI/sneha@okaxis', amount: 800, type: 'debit', category: 'transfer', mode: 'UPI', status: 'completed' },
  { id: 't11', accountId: 'a3', date: d(5, 16, 20), merchant: 'Flipkart', description: 'Apparel order', amount: 3499, type: 'debit', category: 'shopping', mode: 'CARD', status: 'completed' },
  { id: 't12', accountId: 'a1', date: d(6, 19, 0), merchant: 'BookMyShow', description: 'Movie tickets', amount: 450, type: 'debit', category: 'entertainment', mode: 'CARD', status: 'completed' },
  { id: 't13', accountId: 'a2', date: d(7, 10, 0), merchant: 'BESCOM', description: 'Electricity bill', amount: 2340, type: 'debit', category: 'bills', mode: 'BILL', status: 'completed' },
  { id: 't14', accountId: 'a1', date: d(7, 9, 30), merchant: 'Apollo Pharmacy', description: 'Medicines', amount: 680, type: 'debit', category: 'other', mode: 'UPI', status: 'completed' },
  { id: 't15', accountId: 'a1', date: d(8, 17, 15), merchant: 'HP Petrol Pump', description: 'Fuel', amount: 2500, type: 'debit', category: 'transport', mode: 'CARD', status: 'completed' },
  { id: 't16', accountId: 'a1', date: d(8, 8, 0), merchant: 'Jio', description: 'Mobile recharge', amount: 399, type: 'debit', category: 'bills', mode: 'BILL', status: 'completed' },
  { id: 't17', accountId: 'a1', date: d(10, 15, 0), merchant: 'Vikram Iyer', description: 'UPI/vikram@okicici', amount: 2200, type: 'debit', category: 'transfer', mode: 'UPI', status: 'completed' },
  { id: 't18', accountId: 'a3', date: d(11, 13, 25), merchant: 'Decathlon', description: 'Sports gear', amount: 4200, type: 'debit', category: 'shopping', mode: 'CARD', status: 'completed' },
  { id: 't19', accountId: 'a1', date: d(12, 9, 0), merchant: 'ACT Fibernet', description: 'Internet bill', amount: 1099, type: 'debit', category: 'bills', mode: 'BILL', status: 'completed' },
  { id: 't20', accountId: 'a1', date: d(14, 7, 10), merchant: 'IRCTC', description: 'Train booking', amount: 1250, type: 'debit', category: 'transport', mode: 'CARD', status: 'completed' },
  { id: 't21', accountId: 'a1', date: d(15, 18, 30), merchant: 'Cult.fit', description: 'Gym membership', amount: 2499, type: 'debit', category: 'other', mode: 'CARD', status: 'completed' },
  { id: 't22', accountId: 'a2', date: d(18, 12, 0), merchant: 'BigBasket', description: 'Pantry restock', amount: 1820, type: 'debit', category: 'shopping', mode: 'UPI', status: 'completed' },
  { id: 't23', accountId: 'a1', date: d(20, 19, 45), merchant: 'Zomato', description: 'Weekend order', amount: 745, type: 'debit', category: 'food', mode: 'UPI', status: 'completed' },
  { id: 't24', accountId: 'a4', date: d(24, 10, 0), merchant: 'Salary Credit', description: 'Monthly salary - May', amount: 185000, type: 'credit', category: 'salary', mode: 'NEFT', status: 'completed' },
  { id: 't25', accountId: 'a1', date: d(24, 11, 0), merchant: 'Self Transfer', description: 'SBI → HDFC', amount: 120000, type: 'credit', category: 'transfer', mode: 'IMPS', status: 'completed' },
  { id: 't26', accountId: 'a4', date: d(24, 11, 0), merchant: 'Self Transfer', description: 'To HDFC Savings', amount: 120000, type: 'debit', category: 'transfer', mode: 'IMPS', status: 'completed' },
  { id: 't27', accountId: 'a1', date: d(25, 16, 20), merchant: 'Priya Sharma', description: 'UPI/priya@oksbi', amount: 1100, type: 'debit', category: 'transfer', mode: 'UPI', status: 'completed' },
  { id: 't28', accountId: 'a3', date: d(26, 14, 0), merchant: 'Croma', description: 'Headphones', amount: 5999, type: 'debit', category: 'shopping', mode: 'CARD', status: 'completed' },
  { id: 't29', accountId: 'a1', date: d(27, 8, 0), merchant: 'Swiggy', description: 'Breakfast', amount: 295, type: 'debit', category: 'food', mode: 'UPI', status: 'completed' },
  { id: 't30', accountId: 'a1', date: d(28, 22, 0), merchant: 'PVR Cinemas', description: 'Movie + snacks', amount: 1180, type: 'debit', category: 'entertainment', mode: 'CARD', status: 'completed' },
]

export const initialCards: Card[] = [
  {
    id: 'c1',
    accountId: 'a3',
    type: 'credit',
    network: 'Visa',
    last4: '1147',
    holderName: 'AARAV MEHTA',
    expiry: '08/29',
    frozen: false,
    spendLimit: 250000,
    currentSpend: 18750,
    gradient: 'from-blue-700 via-indigo-700 to-purple-800',
  },
  {
    id: 'c2',
    accountId: 'a2',
    type: 'debit',
    network: 'Mastercard',
    last4: '8830',
    holderName: 'AARAV MEHTA',
    expiry: '02/28',
    frozen: false,
    gradient: 'from-slate-700 via-slate-800 to-slate-900',
  },
  {
    id: 'c3',
    accountId: 'a4',
    type: 'debit',
    network: 'RuPay',
    last4: '9902',
    holderName: 'AARAV MEHTA',
    expiry: '11/27',
    frozen: false,
    gradient: 'from-emerald-700 via-teal-800 to-slate-900',
  },
]

const dueIn = (days: number): string => {
  const base = new Date('2026-05-25T10:30:00+05:30')
  base.setDate(base.getDate() + days)
  return base.toISOString()
}

export const initialBills: Bill[] = [
  { id: 'b1', biller: 'BESCOM Electricity', category: 'electricity', amount: 2340, dueDate: dueIn(3), status: 'upcoming', autopay: false },
  { id: 'b2', biller: 'Jio Mobile', category: 'mobile', amount: 399, dueDate: dueIn(5), status: 'upcoming', autopay: true },
  { id: 'b3', biller: 'ACT Fibernet', category: 'internet', amount: 1099, dueDate: dueIn(6), status: 'upcoming', autopay: false },
  { id: 'b4', biller: 'HDFC Credit Card', category: 'credit_card', amount: 18750, dueDate: dueIn(8), status: 'upcoming', autopay: false },
  { id: 'b5', biller: 'Apartment Rent', category: 'rent', amount: 35000, dueDate: dueIn(12), status: 'upcoming', autopay: false },
]

export const initialBeneficiaries: Beneficiary[] = [
  { id: 'be1', name: 'Rahul Singh', accountNumber: '••••2233', ifsc: 'HDFC0001122', bankName: 'HDFC Bank', nickname: 'Rahul' },
  { id: 'be2', name: 'Sneha Patel', accountNumber: '••••4455', ifsc: 'UTIB0003344', bankName: 'Axis Bank', nickname: 'Sneha' },
  { id: 'be3', name: 'Vikram Iyer', accountNumber: '••••6677', ifsc: 'ICIC0005566', bankName: 'ICICI Bank' },
  { id: 'be4', name: 'Priya Sharma', accountNumber: '••••8899', ifsc: 'SBIN0007788', bankName: 'State Bank of India', nickname: 'Priya' },
]

// ─── Investments ───────────────────────────────────────────────────────────────

export const initialHoldings: Holding[] = [
  {
    id: 'h1',
    name: 'Reliance Industries',
    symbol: 'RELIANCE',
    assetClass: 'equity',
    units: 100,
    avgBuyPrice: 2150,
    currentPrice: 2485,
    investedAmount: 215000,
    currentValue: 248500,
    dayChange: 985,
    dayChangePct: 0.40,
    totalGainLoss: 33500,
    totalGainLossPct: 15.58,
  },
  {
    id: 'h2',
    name: 'HDFC Bank',
    symbol: 'HDFCBANK',
    assetClass: 'equity',
    units: 150,
    avgBuyPrice: 1200,
    currentPrice: 1304,
    investedAmount: 180000,
    currentValue: 195600,
    dayChange: -652,
    dayChangePct: -0.33,
    totalGainLoss: 15600,
    totalGainLossPct: 8.67,
  },
  {
    id: 'h3',
    name: 'Mirae Asset Large Cap Fund',
    symbol: 'MALF',
    assetClass: 'mutual_fund',
    units: 3200,
    avgBuyPrice: 112.50,
    currentPrice: 129.00,
    investedAmount: 360000,
    currentValue: 412800,
    dayChange: 1238,
    dayChangePct: 0.30,
    totalGainLoss: 52800,
    totalGainLossPct: 14.67,
  },
  {
    id: 'h4',
    name: 'Axis Bluechip Fund',
    symbol: 'ABF',
    assetClass: 'mutual_fund',
    units: 2100,
    avgBuyPrice: 114.29,
    currentPrice: 129.14,
    investedAmount: 240000,
    currentValue: 271200,
    dayChange: 813,
    dayChangePct: 0.30,
    totalGainLoss: 31200,
    totalGainLossPct: 13.00,
  },
  {
    id: 'h5',
    name: 'Sovereign Gold Bond 2023',
    symbol: 'SGB',
    assetClass: 'gold',
    units: 20,
    avgBuyPrice: 6000,
    currentPrice: 6900,
    investedAmount: 120000,
    currentValue: 138000,
    dayChange: 276,
    dayChangePct: 0.20,
    totalGainLoss: 18000,
    totalGainLossPct: 15.00,
  },
  {
    id: 'h6',
    name: 'SBI Fixed Deposit',
    symbol: 'FD',
    assetClass: 'fd',
    units: 1,
    avgBuyPrice: 500000,
    currentPrice: 532000,
    investedAmount: 500000,
    currentValue: 532000,
    dayChange: 0,
    dayChangePct: 0,
    totalGainLoss: 32000,
    totalGainLossPct: 6.40,
  },
  {
    id: 'h7',
    name: 'EPF Corpus',
    symbol: 'EPF',
    assetClass: 'ppf',
    units: 1,
    avgBuyPrice: 420000,
    currentPrice: 448500,
    investedAmount: 420000,
    currentValue: 448500,
    dayChange: 0,
    dayChangePct: 0,
    totalGainLoss: 28500,
    totalGainLossPct: 6.79,
  },
  {
    id: 'h8',
    name: 'PPFAS Flexi Cap Fund',
    symbol: 'PPFAS',
    assetClass: 'mutual_fund',
    units: 1200,
    avgBuyPrice: 150.00,
    currentPrice: 176.25,
    investedAmount: 180000,
    currentValue: 211500,
    dayChange: 634,
    dayChangePct: 0.30,
    totalGainLoss: 31500,
    totalGainLossPct: 17.50,
  },
]

export const initialSIPs: SIP[] = [
  {
    id: 'sip1',
    holdingId: 'h3',
    name: 'Mirae Asset Large Cap Fund',
    amount: 5000,
    frequency: 'monthly',
    nextDate: dueIn(11),
    status: 'active',
  },
  {
    id: 'sip2',
    holdingId: 'h4',
    name: 'Axis Bluechip Fund',
    amount: 4000,
    frequency: 'monthly',
    nextDate: dueIn(11),
    status: 'active',
  },
  {
    id: 'sip3',
    holdingId: 'h8',
    name: 'PPFAS Flexi Cap Fund',
    amount: 3000,
    frequency: 'monthly',
    nextDate: dueIn(11),
    status: 'active',
  },
]

// ─── Insurance ─────────────────────────────────────────────────────────────────

export const initialPolicies: InsurancePolicy[] = [
  {
    id: 'pol1',
    insurer: 'LIC of India',
    policyType: 'term',
    policyNumber: 'LIC-TERM-2891047',
    coverAmount: 10000000,
    premiumAmount: 12500,
    premiumFrequency: 'annually',
    nextPremiumDate: dueIn(45),
    expiryDate: '2041-07-09',
    status: 'active',
  },
  {
    id: 'pol2',
    insurer: 'Star Health Insurance',
    policyType: 'health',
    policyNumber: 'SH-FAM-2024-66541',
    coverAmount: 1000000,
    premiumAmount: 22000,
    premiumFrequency: 'annually',
    nextPremiumDate: dueIn(90),
    expiryDate: '2027-08-23',
    status: 'active',
  },
  {
    id: 'pol3',
    insurer: 'HDFC ERGO',
    policyType: 'vehicle',
    policyNumber: 'ERGO-VEH-2025-11234',
    coverAmount: 300000,
    premiumAmount: 8500,
    premiumFrequency: 'annually',
    nextPremiumDate: dueIn(120),
    expiryDate: '2027-09-22',
    status: 'active',
  },
  {
    id: 'pol4',
    insurer: 'SBI Life Insurance',
    policyType: 'ulip',
    policyNumber: 'SBI-ULIP-2022-55891',
    coverAmount: 5000000,
    premiumAmount: 36000,
    premiumFrequency: 'annually',
    nextPremiumDate: dueIn(180),
    expiryDate: '2037-11-21',
    status: 'active',
  },
]

// ─── Loans ─────────────────────────────────────────────────────────────────────

export const initialLoans: Loan[] = [
  {
    id: 'ln1',
    lender: 'HDFC Bank',
    loanType: 'home',
    accountNumber: 'HDFC-HL-00234567',
    principalAmount: 7500000,
    outstandingBalance: 4200000,
    emiAmount: 38250,
    interestRate: 8.5,
    tenure: 240,
    remainingTenure: 180,
    nextEmiDate: dueIn(6),
    startDate: '2020-12-01',
    status: 'active',
  },
  {
    id: 'ln2',
    lender: 'ICICI Bank',
    loanType: 'personal',
    accountNumber: 'ICICI-PL-00987654',
    principalAmount: 500000,
    outstandingBalance: 285000,
    emiAmount: 12500,
    interestRate: 12.5,
    tenure: 48,
    remainingTenure: 24,
    nextEmiDate: dueIn(10),
    startDate: '2024-06-01',
    status: 'active',
  },
]

// ─── Financial Goals ───────────────────────────────────────────────────────────

export const initialGoals: FinancialGoal[] = [
  {
    id: 'g1',
    name: 'Emergency Fund',
    category: 'emergency_fund',
    targetAmount: 600000,
    currentAmount: 425000,
    targetDate: '2026-12-31',
    monthlyContribution: 15000,
    status: 'on_track',
  },
  {
    id: 'g2',
    name: 'Europe Trip 2027',
    category: 'vacation',
    targetAmount: 300000,
    currentAmount: 120000,
    targetDate: '2027-06-30',
    monthlyContribution: 8000,
    status: 'on_track',
  },
  {
    id: 'g3',
    name: 'New Car (Down Payment)',
    category: 'vehicle',
    targetAmount: 500000,
    currentAmount: 280000,
    targetDate: '2027-03-31',
    monthlyContribution: 12000,
    status: 'on_track',
  },
  {
    id: 'g4',
    name: "Riya's Education Fund",
    category: 'education',
    targetAmount: 2500000,
    currentAmount: 420000,
    targetDate: '2035-06-30',
    monthlyContribution: 10000,
    status: 'behind',
  },
]

// ─── Property ──────────────────────────────────────────────────────────────────

export const initialPropertyAssets: PropertyAsset[] = [
  {
    id: 'prop1',
    name: '2BHK Apartment',
    location: 'Whitefield, Bengaluru',
    estimatedValue: 8500000,
    purchaseValue: 5500000,
    purchaseDate: '2020-12-01',
  },
]
